### ISSUE TITLE
GRPCIO dependency fails to install on M1 Macs, October 2021. Workaround suggested.

### ISSUE THREAD

**Issue by Athiriyya** [stakewise/oracle#21]
The dependency GRPCIO still seems to have compatibility problems with Arm64 Macs. Installing dependencies with `pip install -r requirements/prod.txt` failed on the GRPCIO step. Discussion of [that particular issue](https://github.com/grpc/grpc/issues/25082#issuecomment-754565768) makes it look like an issue with how OpenSSL is handled, and suggested the following workaround, which worked for me: 

``` shell
# (having created and activated a virtualenv for the Oracle project)
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
pip install -r requirements/prod.txt
# .
# .
# .... build succeeded
``` 

This isn't really a bug and I don't expect any action on it. But it's possible that this issue will appear in someone's search and save them some time. Cheers

**Comment by tsudmi** [comment]
Thanks for writing this issue @Athiriyya . I think there will be definitely m1 users that will benefit from that. Maybe we could add a note to the installation README.

**Comment by tsudmi** [comment]
Closing this as there is no dependency to GRPCIO in V2 oracle anymore.
